name: Build Jekyll Site with Org Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install Emacs and Org-mode
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs pandoc

    - name: Convert .org to .md
      run: |
        mkdir -p _org
        find . -name "*.org" -exec pandoc {} -o _org/{}.md \;

    - name: Copy Markdown to _posts
      run: |
        mkdir -p _posts
        cp _org/*.md _posts/

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
